### ISSUE TITLE
The functions MPCRTile.gemm, MPCR.gemm, and chol might not be exported properly

### ISSUE THREAD

**Issue by tedescolor** [stsds/MPCR#13]
I am interested in the Cholesky and matrix multiplication functions, but there seems to be an error in the export of these functions as they cannot be called. After installing the package, the following errors occur when executing `MPCR/blob/main/tests/R-tests/TestMPCRTile.R`:

At line:
chol_values <- chol(chol_mat, overwrite_input = FALSE, num_thread = 8)

The error is:

Error in as.vector(x, mode) : 
  cannot coerce type 'environment' to vector of type 'any'

At line:

MPCRTile.gemm(a = mat_a, b = mat_b, c = mat_c, transpose_a = FALSE, transpose_b = FALSE, alpha = 1, beta = 1, num_thread = 8)

The error is:
Error in MPCRTile.gemm(a = mat_a, b = mat_b, c = mat_c, transpose_a = FALSE,  : 
  could not find function "MPCRTile.gemm"

**Comment by david-helmy** [comment]
Hey @tedescolor , Which version or branch were you using while you encountered this problem?

**Comment by tedescolor** [comment]
Dear @david-helmy thanks a lot for your answer. I am using version 1.1.2 installed from CRAN by install.packages("MPCR")

**Comment by david-helmy** [comment]
@tedescolor , I will check this issue and reply back to you once fixed. In the meantime you can try installing the package using R CMD INSTALL and see if you still facing the same issue.

**Comment by tedescolor** [comment]
Thanks a lot, in this way the version 1.0 is installed and the issue does not occur.
